### ISSUE TITLE
Logic

### ISSUE THREAD

**Issue by universeluke** [SchoolOfCode/week-2-hackathon-rock-paper-scissors-room12-wk2#1]
```[tasklist]
### Tasks
- [x] Create array of length 4, in order: [Rock, Paper, Scissors, Rock,]
- [x] If value of computer's guess matches value AFTER human's guess, computer wins, so remove 1 from player's score
- [x] Else, player wins, add 1 to player's score
```
